name: Get Sender ID in Script
on:
  push:
    branches:
      - main
jobs:
  get_id:
    runs-on: ubuntu - latest
    steps:
      - name: Set and Use Sender ID in Script
        run: |
          sender_id=${{ github.event.sender.id }}
          echo "The sender ID is: $sender_id"
          # 这里可以继续使用 $sender_id 进行其他操作
